import type { Platform } from "./platform";

export type AttachmentType = "image" | "video" | "file" | "sticker" | "audio";

export interface Attachment {
  type: AttachmentType;
  url: string;
  name?: string;
  size?: number;
  mime?: string;
}

/**
 * Normalized message event — the common schema published to Redis Streams.
 * All platform-specific normalizers must produce this shape.
 */
export interface MessageEvent {
  /** UUID generated by the gateway — used as Redis Stream entry key */
  eventId: string;
  platform: Platform;
  /** Platform-native user/sender ID */
  senderId: string;
  senderName?: string;
  senderAvatar?: string;
  /** Platform-native thread / conversation ID */
  threadId: string;
  /** Platform-native message ID — used for deduplication */
  messageId: string;
  text?: string;
  attachments: Attachment[];
  /** Unix ms — platform timestamp */
  timestamp: number;
  /** Raw platform payload stored for audit; stripped of large binary fields */
  raw?: unknown;
}
